let team3Students = [{
    name: "Vittorio",
  surname: "De Giorgio",
  age: 26,
  city: "Amaroni",
  hobby: "Gym",
  favouriteFood: "Pizza",
  favouriteVideoGame: "The last of us",
  favouriteFilm: "Interstellar",
  favouriteBook: "Io, Ibra",
  petName: "McGiò"
},
{
  name: "Antonino",
  surname: "D'Arpa",
  age: 28,
  city: "Palermo",
  hobby: "Digital Collage",
  favoriteFood: "Lasagne",
  favoriteVideoGame: "7 Wonders",
  favoriteFilm: "American Beauty",
  favoriteBook: "Da Cosa Nasce Cosa",
  petName: "Bobby",
},
{
  name: "leo",
  surname: "sorre",
  age: 27,
  city: "bologna",
  hobby: "GO",
  favoriteFood: "amatriciana",
  favoriteVideoGame: "fallout",
  favoriteFilm: "dune",
  favoriteBook: "dune",
  petName: "Katana",
},
{
  name: "Stefano",
  surname: "Mazzarella",
  age: 21,
  city: "Napoli",
  hobby: "football",
  favoriteFood: "pasta al ragù",
  favoriteVideoGame: "fifa",
  favoriteFilm: "peaky blinders",
  favoriteBook: "la vera storia dei peaky blinders",
  petName: "Roy",
};
];
